package dtos

// Ingredient represents a single ingredient in a recipe.
type Ingredient struct {
	Name   string `json:"name" binding:"required"`
	Amount string `json:"amount" binding:"required"`
	Unit   string `json:"unit" binding:"required"`
}

// Step represents a single step in a recipe.
type Step struct {
	Order       int    `json:"order" binding:"required"`
	Description string `json:"description" binding:"required"`
}

// RecipeRequest defines the payload for creating a new recipe.
// Fields such as ID, CreatedAt, UpdatedAt, and Embedding are generated by the system.
type RecipeRequest struct {
	Title             string       `json:"title" binding:"required"`
	Description       string       `json:"description,omitempty"`
	Ingredients       []Ingredient `json:"ingredients" binding:"required"`
	Steps             []Step       `json:"steps" binding:"required"`
	NutritionalInfo   string       `json:"nutritional_info,omitempty"`
	AllergyDisclaimer string       `json:"allergy_disclaimer,omitempty"`
	Cuisines          []string     `json:"cuisines,omitempty"`
	Diets             []string     `json:"diets,omitempty"`
	Appliances        []string     `json:"appliances,omitempty"`
	Tags              []string     `json:"tags,omitempty"`
	Images            []string     `json:"images,omitempty"`
	Difficulty        string       `json:"difficulty,omitempty"`
	PrepTime          int          `json:"prep_time,omitempty"`
	CookTime          int          `json:"cooking_time,omitempty"`
	Servings          int          `json:"servings,omitempty"`
	Approved          bool         `json:"approved,omitempty"`
}

// RecipeResolutionRequest defines the payload for the /resolve endpoint.
// It accepts the criteria for finding close and/or exact matches.
// If no candidate is acceptable from the database search, additional
// modification instructions can be supplied for the LLM.
type RecipeResolutionRequest struct {
	Title             string   `json:"title" binding:"required"`
	Ingredients       []string `json:"ingredients" binding:"required"`
	Steps             []string `json:"steps" binding:"required"`
	NutritionalInfo   string   `json:"nutritional_info,omitempty"`
	AllergyDisclaimer string   `json:"allergy_disclaimer,omitempty"`
	Appliances        []string `json:"appliances,omitempty"`
	// New fields for filtering by cuisines and diets
	Cuisines []string `json:"cuisines,omitempty"`
	Diets    []string `json:"diets,omitempty"`
	// Tags for recipe categorization and search
	Tags []string `json:"tags,omitempty"`
	// Additional instructions on how to modify or generate a new recipe
	ModificationInstructions string `json:"modification_instructions,omitempty"`
}
