version: "3.9"

services:
  app:
    build: .
    container_name: app
    env_file:
      - .env
    networks:
      - appnet
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "set -x; curl -v http://localhost:8080/v1/health || (echo 'Healthcheck failed with code $?'; exit 1)"]
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ci_password}
      POSTGRES_DB: ${POSTGRES_DB:-ci_recipesdb}
      JWT_SECRET: ${JWT_SECRET:-secret}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      DB_SOURCE: ${DB_SOURCE:-postgres://postgres:ci_password@postgres:5432/ci_recipesdb?sslmode=disable}

  postgres:
    image: ankane/pgvector
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - appnet
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - appnet
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  redis-data:

networks:
  appnet:
    driver: bridge