version: '3.8'
services:
  app:
    build: .
    container_name: app
    env_file:
      - .env.production
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      alchemorsel-network:
        aliases:
          - alchemorsel-service
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://alchemorsel-service:8080/v1/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: ankane/pgvector
    container_name: postgres
    environment:
      POSTGRES_DB: persistent_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - alchemorsel-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - alchemorsel-network

volumes:
  postgres-data:
  redis-data:

networks:
  alchemorsel-network:
    driver: bridge