services:
  app:
    secrets: []

# Override global secrets to be removed so that services referencing them don't try to mount them
secrets:
  jwt_secret: {}
  postgres_user: {}
  postgres_password: {} 