cluster.name: alchemorsel
node.name: elasticsearch
network.host: 0.0.0.0
discovery.type: single-node
xpack.security.enabled: true
xpack.monitoring.enabled: true
xpack.watcher.enabled: true

# Memory settings
bootstrap.memory_lock: true
indices.memory.index_buffer_size: 30%

# Logging settings
logger.level: INFO
logger.type: file
logger.file: /var/log/elasticsearch/elasticsearch.log

# Index settings
index.number_of_shards: 1
index.number_of_replicas: 0
index.refresh_interval: 1s

# Snapshot settings
path.repo: ["/usr/share/elasticsearch/backups"]
snapshot.max_concurrent_snapshots: 2

# Security settings
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/certificates/elasticsearch.key
xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/certificates/elasticsearch.crt
xpack.security.transport.ssl.certificate_authorities: ["/usr/share/elasticsearch/config/certificates/ca.crt"] 