# Logging Configuration

# File logging settings
file:
  directory: "logs"
  max_size: 100    # MB
  max_backups: 5
  max_age: 30      # days
  compress: true

# Console logging settings
console:
  enabled: true
  level: "info"
  format: "json"   # json or text
  color: true

# Elasticsearch logging settings
elasticsearch:
  enabled: true
  url: "http://localhost:9200"
  index: "alchemorsel-logs"
  bulk_size: 1000
  flush_interval: "5s"
  retry_count: 3
  retry_delay: "1s"

# Log levels and their corresponding numeric values
levels:
  debug: 0
  info: 1
  warn: 2
  error: 3
  fatal: 4

# Request ID settings
request_id:
  header: "X-Request-ID"
  length: 32
  prefix: "req-"

# Log rotation settings
rotation:
  enabled: true
  max_size: 100    # MB
  max_backups: 5
  max_age: 30      # days
  compress: true
  compress_old: 7  # days

# Log aggregation settings
aggregation:
  enabled: true
  batch_size: 100
  flush_interval: "5s"
  max_retries: 3
  retry_delay: "1s"

# Log analysis settings
analysis:
  enabled: true
  patterns:
    - name: "error_rate"
      query: "level:error"
      window: "5m"
      threshold: 10
    - name: "high_latency"
      query: "fields.latency:>1000"
      window: "1m"
      threshold: 5
    - name: "api_errors"
      query: "level:error AND service:api"
      window: "5m"
      threshold: 20

# Log search settings
search:
  enabled: true
  max_results: 1000
  default_time_range: "24h"
  highlight_fields:
    - "message"
    - "fields.*"
  sort_fields:
    - "@timestamp"
    - "level"

# Log compression settings
compression:
  enabled: true
  algorithm: "gzip"
  level: 6
  min_size: 1024  # bytes
  max_age: 7      # days

# Security settings
security:
  sensitive_fields:
    - "password"
    - "token"
    - "api_key"
  mask_pattern: "********"
  audit_logging: true
  audit_events:
    - "login"
    - "logout"
    - "password_change"
    - "role_change" 