groups:
  - name: system
    rules:
      - alert: HighCPUUsage
        expr: avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) < 0.2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage
          description: CPU usage is above 80% for 5 minutes

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage
          description: Memory usage is above 85% for 5 minutes

      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High disk usage
          description: Disk usage is above 85% for 5 minutes

  - name: application
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate
          description: Error rate is above 5% for 5 minutes

      - alert: SlowResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Slow response time
          description: 95th percentile of response time is above 1 second

      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Service is down
          description: Service {{ $labels.instance }} is down

  - name: database
    rules:
      - alert: HighDatabaseConnections
        expr: pg_stat_activity_count > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High database connections
          description: Database connection count is above 100

      - alert: SlowQueries
        expr: rate(pg_stat_activity_max_tx_duration{datname!~"template.*"}[5m]) > 300
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Slow queries detected
          description: Queries running longer than 5 minutes

  - name: redis
    rules:
      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Redis is down
          description: Redis instance {{ $labels.instance }} is down

      - alert: RedisMemoryHigh
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High Redis memory usage
          description: Redis memory usage is above 85%

  - name: slos
    rules:
      - alert: AvailabilitySLO
        expr: sum(rate(http_requests_total{status=~"5.."}[1h])) / sum(rate(http_requests_total[1h])) > 0.01
        for: 1h
        labels:
          severity: critical
        annotations:
          summary: Availability SLO breached
          description: Error rate above 1% for 1 hour

      - alert: LatencySLO
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[1h])) > 0.5
        for: 1h
        labels:
          severity: critical
        annotations:
          summary: Latency SLO breached
          description: 95th percentile of response time is above 500ms for 1 hour

  - name: anomalies
    rules:
      - alert: AnomalousTraffic
        expr: |
          rate(http_requests_total[5m]) > 
          avg(rate(http_requests_total[1h])) + 2 * stddev(rate(http_requests_total[1h]))
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Anomalous traffic detected
          description: Traffic is significantly higher than normal 