# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker
        uses: docker/setup-qemu-action@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Run Unit Tests
        run: go test -v ./tests/unit/...

      - name: Run Integration Tests
        run: go test -v ./tests/integration/...

      - name: Set environment variable for CI
        run: echo "MY_ENV_FILE=.env.ci" >> $GITHUB_ENV

      - name: Load environment variables from .env.ci
        run: |
          if [ -f .env.ci ]; then
            export $(grep -v '^#' .env.ci | xargs)
          else
            echo ".env.ci file not found!"
            exit 1
          fi

      - name: Create Docker network for E2E tests
        run: docker network create ci_network || true

      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for Postgres to be ready on port 5432..."
          for i in {1..10}; do
            if nc -z localhost 5432; then
              echo "Postgres is ready!"
              exit 0
            fi
            echo "Waiting... ($i/10)"
            sleep 5
          done
          echo "Postgres did not become ready in time."
          exit 1

      - name: Print current directory contents
        run: ls -la

      - name: Run service container for E2E tests using docker-compose
        run: docker compose --env-file .env.ci up -d

      - name: Check PostgreSQL logs
        run: docker logs postgres || true

      - name: Wait for service to be ready
        run: |
          echo "Waiting for recipeservice to be ready on port 8080..."
          for i in {1..10}; do
            if nc -z localhost 8080; then
              echo "recipeservice is up!"
              exit 0
            fi
            echo "Waiting... ($i/10)"
            sleep 5
          done
          echo "recipeservice did not become ready in time."
          exit 1

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman E2E tests
        run: newman run tests/collections/user_endpoints.postman_collection.json --delay-request 500

      - name: Cleanup E2E containers
        if: always()
        run: |
          docker compose down
          docker stop ci_postgres || true
          docker rm ci_postgres || true
          docker network rm ci_network || true

      - name: Print Docker logs
        if: always()
        run: docker logs recipeservice

      - name: Stop Docker container
        if: always()
        run: docker compose down 