# API Configuration

# API Documentation
documentation:
  enabled: true
  title: "Alchemorsel API"
  description: "API for the Alchemorsel application"
  version: "1.0.0"
  contact:
    name: "Alchemorsel Team"
    email: "support@alchemorsel.com"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
  servers:
    - url: "/api/v1"
      description: "API v1"
    - url: "/api/v2"
      description: "API v2"

# API Versioning
versioning:
  enabled: true
  versions:
    - "1.0.0"
    - "2.0.0"
  default_version: "2.0.0"
  version_header: "X-API-Version"
  version_param: "version"
  version_path: true

# Request Validation
validation:
  enabled: true
  rules:
    # Common validation rules
    email:
      pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
      message: "Invalid email format"
    
    password:
      min_length: 8
      require_uppercase: true
      require_lowercase: true
      require_numbers: true
      require_special: true
      message: "Password must be at least 8 characters and contain uppercase, lowercase, numbers, and special characters"
    
    username:
      min_length: 3
      max_length: 50
      pattern: "^[a-zA-Z0-9_-]+$"
      message: "Username must be 3-50 characters and contain only letters, numbers, underscores, and hyphens"
    
    # Custom validation rules
    custom:
      phone:
        pattern: "^\\+?[1-9]\\d{1,14}$"
        message: "Invalid phone number format"
      
      date:
        format: "2006-01-02"
        message: "Invalid date format"
      
      time:
        format: "15:04:05"
        message: "Invalid time format"

# Response Validation
response:
  enabled: true
  rules:
    # Common response rules
    pagination:
      max_page_size: 100
      default_page_size: 20
    
    sorting:
      allowed_fields:
        - "created_at"
        - "updated_at"
        - "name"
        - "email"
      default_sort: "created_at"
      default_order: "desc"
    
    filtering:
      allowed_fields:
        - "status"
        - "type"
        - "category"
      max_filters: 5

# API Security
security:
  enabled: true
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "https://alchemorsel.com"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "PATCH"
    allowed_headers:
      - "Authorization"
      - "Content-Type"
      - "X-API-Version"
    exposed_headers:
      - "X-Request-ID"
      - "X-RateLimit-Limit"
      - "X-RateLimit-Remaining"
    allow_credentials: true
    max_age: 86400  # 24 hours

# Rate Limiting
rate_limit:
  enabled: true
  default_limit: 100
  window: 60  # seconds
  storage: "redis"
  redis:
    host: "localhost"
    port: 6379
    db: 0
  rules:
    - path: "/api/v1/auth/*"
      limit: 5
      window: 60
    - path: "/api/v1/users/*"
      limit: 50
      window: 60
    - path: "/api/v1/admin/*"
      limit: 20
      window: 60

# Error Handling
error_handling:
  enabled: true
  format: "json"
  include_stack_trace: false
  sanitize_errors: true
  custom_errors:
    - code: "VALIDATION_ERROR"
      status: 400
      message: "Validation failed"
    - code: "NOT_FOUND"
      status: 404
      message: "Resource not found"
    - code: "UNAUTHORIZED"
      status: 401
      message: "Unauthorized"
    - code: "FORBIDDEN"
      status: 403
      message: "Forbidden"
    - code: "INTERNAL_ERROR"
      status: 500
      message: "Internal server error"

# Monitoring
monitoring:
  enabled: true
  metrics:
    enabled: true
    path: "/metrics"
    interval: 15  # seconds
  tracing:
    enabled: true
    sampler: 1.0
    exporter: "jaeger"
    jaeger:
      endpoint: "http://localhost:14268/api/traces"
  logging:
    enabled: true
    level: "info"
    format: "json"
    fields:
      - "request_id"
      - "user_id"
      - "duration"
      - "status"
      - "path"
      - "method" 